### ISSUE TITLE
[Bug] Register page is blank

### ISSUE THREAD

**Issue by AzamServer** [JackBailey/Lynx#13]
Whenever I open the register page, it's just a blank black page with the word "Register" in a big white font, and the words "Already have an account? Log in" in a smaller blue font right below it. I haven't created any user account yet. An image and all the docker files are below.

Error page:
![Screenshot 2023-02-25 at 10 17 52 PM](https://user-images.githubusercontent.com/78570129/221390447-0c3c66f5-6cd0-473a-add8-e4b1f8b169de.png)

docker-compose.yml:
```yml
version: "3"
services:
    db:
        image: mongo:latest
        container_name: lnyx-db
        restart: unless-stopped
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=[1st 32 alphanumeric code]
        volumes:
            - ./config/db:/data/db

    lynx:
        image: jackbailey/lynx
        container_name: lynx-lynx
        restart: unless-stopped
        ports:
            - 3000:3000
        depends_on:
            - db
        environment:
            - NODE_ENV=production
            - DB_USER=admin
            - DB_PASSWORD=[1st 32 alphanumeric code]
            - JWT_KEY=[2nd 32 alphanumeric code]
            - URL_LENGTH=8
            - URL_SET=standard
            - URL_ONLY_UNIQUE=true
            - HOME_REDIRECT=/dash/overview
            - FORCE_FRONTEND_REDIRECT=true
            - ENABLE_REGISTRATION=true
            - DOMAIN=[my domain]
            - DEMO=false
            - DB_HOST=db
            - DB_PORT=27017
```
