### ISSUE TITLE
Reloading the page logouts the account

### ISSUE THREAD

**Issue by Entheologian** [JackBailey/Lynx#14]
I am using the docker version, and when logged in to http://host:3000 (without reverse proxy) everything works but if I refresh the page, I have to re-login. Is this expected?

**Comment by JackBailey** [comment]
I'll take a look today, apologies for the delay, I didn't get a notification

**Comment by JackBailey** [comment]
Seems to be keeping me logged in fine @Entheologian, what does your docker compose file look like and what OS + Browser are you running?

**Comment by Entheologian** [comment]
Sorry for late reply!

I updated and tried again, but same issue. I tried with two desktop browsers (chromium and brave) and also on android brave browser, but all three do the same so far when I refresh the page (bring me back to the login page).

docker-compose.yml:
```
version: "3"
services:
    db:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=secret_password
        volumes:
            - ./db:/data/db

    lynx:
        image: jackbailey/lynx
        restart: always
        ports:
            - 3000:3000
        depends_on:
            - db
        environment:
            - NODE_ENV=production
            - DB_USER=admin
            - DB_PASSWORD=secret_password
            - JWT_KEY="xxxxxxx--obfuscated--xxxxxx="
            - URL_LENGTH=8
            - URL_SET=standard
            - URL_ONLY_UNIQUE=false
            - HOME_REDIRECT=/dash/overview
            - FORCE_FRONTEND_REDIRECT=false
            - ENABLE_REGISTRATION=true # First registration will always be allowed
            - DOMAIN=http://docker
            - DEMO=false

            ## DO NOT CHANGE THESE:
            - DB_HOST=db
            - DB_PORT=27017
```

**Comment by JackBailey** [comment]
Is there anything in the browser's console after refreshing? I'm thinking it might be a cookie issue maybe

**Comment by Entheologian** [comment]
For more detail, this is what it shows when expanded:
```
GET http://docker:3000/api/auth/me 401 (Unauthorized) account-aeec9fd0.js:1
fetch	@	account-aeec9fd0.js:1
(anonymous)	@	preload-helper-e8887c78.js:1
getAccount	@	account-aeec9fd0.js:1
(anonymous)	@	preload-helper-e8887c78.js:1
(anonymous)	@	index-759e6933.js:1
(anonymous)	@	index-759e6933.js:1
(anonymous)	@	index-759e6933.js:1
(anonymous)	@	index-759e6933.js:1
Promise.then (async)		
(anonymous)	@	index-759e6933.js:1
Ut	@	index-759e6933.js:1
(anonymous)	@	index-759e6933.js:1
Promise.then (async)		
I	@	index-759e6933.js:1
x	@	index-759e6933.js:1
b	@	index-759e6933.js:1
install	@	index-759e6933.js:1
use	@	preload-helper-e8887c78.js:1
(anonymous)	@	index-759e6933.js:760
```

**Comment by JackBailey** [comment]
Is there anything in the console when you log in?

**Comment by Entheologian** [comment]
I tried it again just now and this is what I see on the console after login (refresh kicks me out, but nothing in console after):
> [...]
> lynx_1  | Listening on port 3000
> lynx_1  | Backend started!
> 

After login:
> db_1    | {"t":{"$date":"2023-03-29T09:38:29.555+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"10.16.0.6:52006","uuid":"c5151c0d-b0e4-46b1-b2bc-3b125e7a6cca","connectionId":5,"connectionCount":5}}
> db_1    | {"t":{"$date":"2023-03-29T09:38:29.558+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn5","msg":"client metadata","attr":{"remote":"10.16.0.6:52006","client":"conn5","doc":{"driver":{"name":"nodejs|Mongoose","version":"4.12.1"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.10.0-21-amd64"},"platform":"Node.js v18.14.2, LE (unified)","version":"4.12.1|6.8.0"}}}

**Comment by JackBailey** [comment]
Okay nothing in the server's console is good at least.
Try turning on recording mode on the browser console so you can see what it logs incase it refreshes

**Comment by Entheologian** [comment]
When I load the browser console and hit refresh, I see this again but using another test host:
 GET http://bete.home.lan:4000/api/auth/me 401 (Unauthorized)

**Comment by JackBailey** [comment]
After you type in your details and click login is there anything? I'm thinking there might be an issue with the cookie being set

**Comment by Entheologian** [comment]
After I login, no errors or anything... All looks good, until I hit refresh then I am back at the login prompt. =(

**Comment by JackBailey** [comment]
Managed to recreate this using my LAN ip, I'll let you know when I fix it

**Comment by Entheologian** [comment]
Cool, now I'm not alone anymore.. lol.

**Comment by Entheologian** [comment]
I did a docker pruning of everything to clean up, re-pulled and re-started but same issue. 

As for cloning and building, I can clone it but I am not sure of the docker build steps to do that. If you want me to try this way instead (clone & build), then I'll gladly give that a try too, but just need the build steps, ie make build?

**Comment by JackBailey** [comment]
> I did a docker pruning of everything to clean up, re-pulled and re-started but same issue.

I haven't added these changes to the dockerhub image yet


I did a docker pruning of everything to clean up, re-pulled and re-started but same issue.

> then I'll gladly give that a try too, but just need the build steps, ie make build?

Sure, you should just need to:

Clone the repo:

```
git clone https://github.com/JackBailey/Lynx
```

Navigate into the directory

```
cd Lynx
```

Switch to the http-cookie branch

```
git switch http-cookie
```

Edit the docker-compose.yml to your liking but replace `image: jackbailey/lynx` with: `build: .`

Then start it:

```
docker compose up --force-recreate --build
```

This _should_ work

**Comment by Entheologian** [comment]
> I haven't added these changes to the dockerhub image yet
Ahhhh, that's why. =)

Here's my modified test docker-compose.yml file:
```
version: "3"
services:
    db:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=pass123
        volumes:
            - ./db:/data/db
        networks:
            - lynx

    lynx:
        #image: jackbailey/lynx
        build: .
        restart: always
        ports:
            - 4000:3000
        depends_on:
            - db
        environment:
            - NODE_ENV=production
            - DB_USER=admin
            - DB_PASSWORD=pass123
            - JWT_KEY="SJfYoO7K4hgFrZK0K2TTEvF1pQ41+RXawE4auhXx5iw="
            - URL_LENGTH=8
            - URL_SET=standard
            - URL_ONLY_UNIQUE=false
            - HOME_REDIRECT=/dash/overview
            - FORCE_FRONTEND_REDIRECT=false
            - ENABLE_REGISTRATION=false # First registration will always be allowed
            - DOMAIN=http://bete.home.lan
            - DEMO=false

            ## DO NOT CHANGE THESE:
            - DB_HOST=db
            - DB_PORT=27017
        networks:
            - lynx

networks:
  lynx:
    external: true
```

When I fired it up, I see this in the logs:
```
lynx_1  | Couldn't connect to database!
lynx_1  | MongoServerError: Authentication failed.
lynx_1  |     at Connection.onMessage (/app/node_modules/mongodb/lib/cmap/connection.js:230:30)
lynx_1  |     at MessageStream.<anonymous> (/app/node_modules/mongodb/lib/cmap/connection.js:61:60)
lynx_1  |     at MessageStream.emit (node:events:513:28)
lynx_1  |     at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
lynx_1  |     at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
lynx_1  |     at writeOrBuffer (node:internal/streams/writable:392:12)
lynx_1  |     at _write (node:internal/streams/writable:333:10)
lynx_1  |     at Writable.write (node:internal/streams/writable:337:10)
lynx_1  |     at Socket.ondata (node:internal/streams/readable:766:22)
lynx_1  |     at Socket.emit (node:events:513:28) {
lynx_1  |   ok: 0,
lynx_1  |   code: 18,
lynx_1  |   codeName: 'AuthenticationFailed',
lynx_1  |   connectionGeneration: 0,
lynx_1  |   [Symbol(errorLabels)]: Set(2) { 'HandshakeError', 'ResetPool' }
lynx_1  | }
```

**Comment by JackBailey** [comment]
You shouldn't need the custom lynx network I don't think.

If you do want to use it though for some reason set a `container_name` for the db to `lynx-db` and change lynx's DB_HOST to `lynx-db`

**Comment by JackBailey** [comment]
Also you left your JWT key in your config so change that if you're exposing this :)

**Comment by Entheologian** [comment]
I am still relatively new to docker but the reason I had to put the network there was a workaround because I was getting these alerts, unless there's a better way to manage a profusion of services in Docker?
```
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
```

I changed the file as you suggested, added a container_name and defined that as the DB host, but same issue. I then stopped another service (to free a network), removed my network entries and reverted back to the config without those network portions I added, but still same issue:
```
lynx_1  | Couldn't connect to database!
lynx_1  | MongoServerError: Authentication failed.
lynx_1  |     at Connection.onMessage (/app/node_modules/mongodb/lib/cmap/connection.js:230:30)
lynx_1  |     at MessageStream.<anonymous> (/app/node_modules/mongodb/lib/cmap/connection.js:61:60)
lynx_1  |     at MessageStream.emit (node:events:513:28)
lynx_1  |     at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
lynx_1  |     at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
lynx_1  |     at writeOrBuffer (node:internal/streams/writable:392:12)
lynx_1  |     at _write (node:internal/streams/writable:333:10)
lynx_1  |     at Writable.write (node:internal/streams/writable:337:10)
lynx_1  |     at Socket.ondata (node:internal/streams/readable:766:22)
lynx_1  |     at Socket.emit (node:events:513:28) {
lynx_1  |   ok: 0,
lynx_1  |   code: 18,
lynx_1  |   codeName: 'AuthenticationFailed',
lynx_1  |   connectionGeneration: 0,
lynx_1  |   [Symbol(errorLabels)]: Set(2) { 'HandshakeError', 'ResetPool' }
lynx_1  | }
```

The JWT key is only temporary, for testing and will be changed along with the password.  =)

**Comment by JackBailey** [comment]
What does your config look like now?

**Comment by Entheologian** [comment]
```
version: "3"
services:
    db:
        image: mongo
          #container_name: lynx-db
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=pass123
        volumes:
            - ./db:/data/db
              #        networks:
              #            - lynx

    lynx:
        #image: jackbailey/lynx
        build: .
        restart: always
        ports:
            - 4000:3000
        depends_on:
            - db
        environment:
            - NODE_ENV=production
            - DB_USER=admin
            - DB_PASSWORD=pass123
            - JWT_KEY="SJfYoO7K4hgFrZK0K2TTEvF1pQ41+RXawE4auhXx5iw="
            - URL_LENGTH=8
            - URL_SET=standard
            - URL_ONLY_UNIQUE=false
            - HOME_REDIRECT=/dash/overview
            - FORCE_FRONTEND_REDIRECT=false
            - ENABLE_REGISTRATION=false # First registration will always be allowed
            - DOMAIN=http://bete.home.lan
            - DEMO=false

            ## DO NOT CHANGE THESE:
            - DB_HOST=db
              #- DB_HOST=lynx-db
            - DB_PORT=27017
              #        networks:
              #            - lynx

              #networks:
              #  lynx:
              #    external: true
```

**Comment by JackBailey** [comment]
Try either:

Uncomment your host_db line, networks and your db's container_name line

Or

Uncomment your host_db line and set it to db

**Comment by Entheologian** [comment]
The DB_HOST is already set to db and if I un-comment the network lines, container_name and change db_host to lynx-db, I get the same results.

**Comment by Entheologian** [comment]
The host is Debian 11.6 and it's running 44 webapps at the moment and I have tried pruning the networks but they're all in use so it won't remove those, which is why I had to create new networks and add some services onto those networks.

I tried your docker-compse.yml and same issue:
```
lynx_1  | Couldn't connect to database!                                                                                                              
lynx_1  | MongoServerError: Authentication failed.
lynx_1  |     at Connection.onMessage (/app/node_modules/mongodb/lib/cmap/connection.js:230:30)
lynx_1  |     at MessageStream.<anonymous> (/app/node_modules/mongodb/lib/cmap/connection.js:61:60)
lynx_1  |     at MessageStream.emit (node:events:513:28)
lynx_1  |     at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
lynx_1  |     at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
lynx_1  |     at writeOrBuffer (node:internal/streams/writable:392:12)
lynx_1  |     at _write (node:internal/streams/writable:333:10)
lynx_1  |     at Writable.write (node:internal/streams/writable:337:10)
lynx_1  |     at Socket.ondata (node:internal/streams/readable:766:22)
lynx_1  |     at Socket.emit (node:events:513:28) {
lynx_1  |   ok: 0,
lynx_1  |   code: 18,
lynx_1  |   codeName: 'AuthenticationFailed',
lynx_1  |   connectionGeneration: 0,
lynx_1  |   [Symbol(errorLabels)]: Set(2) { 'HandshakeError', 'ResetPool' }
lynx_1  | }
```

What then tried was connecting to the DB, but it's not accepting this username/password:
```
root@12bcb39abd39:/# mongosh -u admin -p pass123
Current Mongosh Log ID: 6426a2713528f4cb944641dc
Connecting to:          mongodb://<credentials>@127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.8.0
MongoServerError: Authentication failed.
```

I does accept without a username/password:
```
root@12bcb39abd39:/# mongosh 
Current Mongosh Log ID: 6426a27ea246d51a66747c45
Connecting to:          mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.8.0
Using MongoDB:          6.0.5
Using Mongosh:          1.8.0

For mongosh info see: https://docs.mongodb.com/mongodb-shell/

test>
```

So then if I set the docker-compse.yml with blank values (as was the case after the build) and trying to start it, shows this:
```
lynx_1  | Couldn't connect to database!
lynx_1  | MongoParseError: URI contained empty userinfo section
lynx_1  |     at new ConnectionString (/app/node_modules/mongodb-connection-string-url/lib/index.js:111:27)
lynx_1  |     at parseOptions (/app/node_modules/mongodb/lib/connection_string.js:200:17)
lynx_1  |     at new MongoClient (/app/node_modules/mongodb/lib/mongo_client.js:45:63)
lynx_1  |     at /app/node_modules/mongoose/lib/connection.js:802:16
lynx_1  |     at new Promise (<anonymous>)
lynx_1  |     at Connection.openUri (/app/node_modules/mongoose/lib/connection.js:799:19)
lynx_1  |     at /app/node_modules/mongoose/lib/index.js:417:10
lynx_1  |     at /app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5
lynx_1  |     at new Promise (<anonymous>)
lynx_1  |     at promiseOrCallback (/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)
```

That's when I run with this config:
```
version: "3"
services:
    db:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=
            - MONGO_INITDB_ROOT_PASSWORD=
        volumes:
            - ./db:/data/db
    lynx:
        #image: jackbailey/lynx
        build: .
        restart: always
        ports:
            - 4000:3000
        depends_on:
            - db
        environment:
            - NODE_ENV=production
            - DB_USER=
            - DB_PASSWORD=
            - JWT_KEY="SJfYoO7K4hgFrZK0K2TTEvF1pQ41+RXawE4auhXx5iw="
            - URL_LENGTH=8
            - URL_SET=standard
            - URL_ONLY_UNIQUE=false
            - HOME_REDIRECT=/dash/overview
            - FORCE_FRONTEND_REDIRECT=false
            - ENABLE_REGISTRATION=false # First registration will always be allowed
            - DOMAIN=http://bete.home.lan
            - DEMO=false

            ## DO NOT CHANGE THESE:
            - DB_HOST=db
            - DB_PORT=27017
```

Then I tried with just username admin (both entries with blank passwords) and that didn't work either:
```
Attaching to lynx_db_1, lynx_lynx_1
db_1    | 
db_1    | error: missing 'MONGO_INITDB_ROOT_USERNAME' or 'MONGO_INITDB_ROOT_PASSWORD'
db_1    |        both must be specified for a user to be created
db_1    | 
lynx_db_1 exited with code 1
db_1    | 
db_1    | error: missing 'MONGO_INITDB_ROOT_USERNAME' or 'MONGO_INITDB_ROOT_PASSWORD'
db_1    |        both must be specified for a user to be created
db_1    | 
db_1    | 
db_1    | error: missing 'MONGO_INITDB_ROOT_USERNAME' or 'MONGO_INITDB_ROOT_PASSWORD'
db_1    |        both must be specified for a user to be created
db_1    | 
lynx_db_1 exited with code 1
```
